### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by ghost** [josefkenny/usercount#6]
Hi,
I've a got a "locale" problem between Mastodon and usercount bot. When i put in .env.production file of Mastodon : 
DEFAULT_LOCALE=fr
then usercount stop working and give an error : 

Traceback (most recent call last):
  File "usercount.py", line 98, in <module>
    current_id = int( get_between(pagecontent, "Home to</span><strong>", "</strong><span>users").replace(",", ""))
  File "usercount.py", line 92, in get_between
    return s[(s.index(substring1)+len(substring1)):s.index(substring2)]
ValueError: substring not found

**Comment by csabyka** [comment]
its caused by these lines: 
Get the number of users, removing commas
current_id = int( get_between(pagecontent, "Home to</span><strong>", "</strong><span>users").replace(",", ""))

Get the number of toots, removing commas
num_toots = int (get_between(pagecontent, "Who authored</span><strong>", "</strong><span>statuses").replace(",", ""))

try to replace Home to, users, Who authored and statuses .
