### ISSUE TITLE
I can't run the bot

### ISSUE THREAD

**Issue by neoranger** [josefkenny/usercount#8]
When i run the bot i get this error:

```
Traceback (most recent call last):
  File "/home/mastodon/.local/lib/python2.7/site-packages/mastodon/Mastodon.py", line 422, in status_post
    media_ids_proper.append(media_id["id"])
KeyError: 'id'
Traceback (most recent call last):
  File "usercount.py", line 199, in <module>
    mastodon.status_post(toot_text, in_reply_to_id=None, media_ids=[media_dict] )
  File "/home/mastodon/.local/lib/python2.7/site-packages/mastodon/Mastodon.py", line 428, in status_post
    raise MastodonIllegalArgumentError("Invalid media dict: %s" % e)
mastodon.Mastodon.MastodonIllegalArgumentError: Invalid media dict: 'id'
```
Can you help me? Thanks!

**Comment by clement-analogue** [comment]
Similar error on Ubuntu Xenial 16.04 with python 2.7.12

```
Uploading graph.png...
Uploaded file, returned:
{u'error': u'Validation failed: File content type is invalid, File is invalid'}
Tooting...
4 accounts 
+1 in the last hour

Traceback (most recent call last):
  File "usercount.py", line 199, in <module>
    mastodon.status_post(toot_text, in_reply_to_id=None, media_ids=[media_dict] )
  File "/usr/local/lib/python2.7/dist-packages/mastodon/Mastodon.py", line 517, in status_post
    raise MastodonIllegalArgumentError("Invalid media dict: %s" % e)
mastodon.Mastodon.MastodonIllegalArgumentError: Invalid media dict: 'id'
```

**Comment by clement-analogue** [comment]
Line 182, change

`media_dict = mastodon.media_post(file_to_upload,"image/png")`

by

`media_dict = mastodon.media_post(file_to_upload)`

**Comment by neoranger** [comment]
@clement-analogue Excellent man! Thanks!!
